site_name: 渔夫量化用户手册
site_description: Test description

repo_name: yufuquant
repo_url: https://github.com/yufuquant/yufuquant
edit_uri: "https://github.com/yufuquant/yufuquant/tree/master/docs/"
use_directory_urls: true

theme:
  name: "material"
  language: "zh"
  feature:
    tabs: true

nav:
  - 介绍: "index.md"
  - 快速使用: "quickstart.md"
  - 交易所凭据: "credential.md"
  - 交易策略: "strategy.md"
  - 机器人: "robot.md"
  - 管理台:
      - 介绍: "admin/index.md"
      - 账户: "admin/account.md"
      - 认证令牌: "admin/auth_token.md"
      - 交易所: "admin/exchange.md"
      - 机器人: "admin/robot.md"
      - 机器人资产记录: "admin/robot_asset_record.md"
  - 附录:
      - 交易对信息: "appendixes/pair.md"

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
